apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ns-matteo
  name: alb-ingress-locust
  labels:
    app: ingress

  annotations:
    alb.ingress.kubernetes.io/group.name: albfe-locust
    alb.ingress.kubernetes.io/target-type: instance # "instance" mode will route traffic to all ec2 instances within cluster on NodePort opened for your service
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8089}, {"HTTP": 80}]'
    # alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30
    alb.ingress.kubernetes.io/inbound-cidrs: "89.186.39.0/24"
    alb.ingress.kubernetes.io/tags: Servizio=Infrastruttura,RepartoCompetenza=Sistemi
  finalizers:
  - ingress.k8s.aws/resources
# spec:
#   ingressClassName: alb
#   rules:
#     - host: hopless-eks-tools.passstage.cloud
#       http:
#         paths:
#           - pathType: Prefix # https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types
#             path: /master
#             backend:
#               service:
#                 name: locust-master
#                 port:
#                   number: 8089
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: locust-master
      port:
        number: 8089