apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: locust-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: locust-worker
  minReplicas: 4
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60