apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-configmap
data:
  ATTACKED_HOST: http://locust-master:8089
  jwt_token.txt: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzM4NCJ9.eyJpZCI6IjQ2NTQzMzU0NDg2MGFjYzVkYzY3YWI4ZDc2ZjEzODVhYTRmZDZjYzgiLCJqdGkiOiI0NjU0MzM1NDQ4NjBhY2M1ZGM2N2FiOGQ3NmYxMzg1YWE0ZmQ2Y2M4IiwiaXNzIjoiXC9EQz1pdFwvREM9cGFzc2NvbVwvT1U9dXRlbnRpXC9DTj1zaWduYXR1cmUtMDEiLCJhdWQiOlsiaHR0cHM6XC9cL3NlcnZpemlwYXNzaHVidGVzdC5wYXNzZXBhcnRvdXQuY2xvdWQiXSwic3ViIjoiMTkxOTAwNjAwMCIsImV4cCI6MTY5OTYxMzA3MSwiaWF0IjoxNjk5NjA5NDcxLCJ0b2tlbl90eXBlIjoiYmVhcmVyIiwic2NvcGUiOiJzZGkiLCJodHRwczpcL1wvaWRwLnBhc3Njb20uaXRcL2RvbWluaW8iOiIifQ.eeE2wTH6s_9Wy-mTKvq__m6x0PYejUqUITrEnm9hwMc2XidTKQr_3n93yo3i_VmPJ8fT3GkcCwI-o6_SQjo6Zoj3t43GcEmsbxTFKAMcIVeOhYOFlV9Hdlyzrrwx9pIXmInTrii9cG-mtCyX8VNtbOKtkQhFbsIARB8rcOmoajM7w76hoDPy3xZ9BpgK0SKD4W4BCLzZCPnr6iPWBtLPFolwZqFVQ-o33neMdu0AMqDHyvnQkdUELVP3a7FbTIzrlACEbNFVXfU0Bq399PP48oQiaAe2fusuaCsx9_06uRmawWKfZDo97kMBpEHzgSrOwt2ERAROXXYl40HKLroDKA
  basic.py: |
  
    from locust import FastHttpUser, TaskSet, task, between ,constant, events
    from locust.runners import MasterRunner
    import requests , json


    #https://servizipasshub.passstage.cloud

    idinstallazione = "1919006000"



    # @events.init.add_listener
    # def on_locust_init(environment, **kwargs):
    #     if isinstance(environment.runner, MasterRunner):
    #         print("I'm on master node")
    #     else:
    #         print("I'm on a worker or standalone node")
    #         endpoint_url = "https://idp.passcom.local/token/jwt"
    #         cert_key_path = "./1919006000.key"
    #         cert_path = "./1919006000.pem"
    #         ca_cert_path = "./ca-staging.pem"
    #         passhub_url = "https://servizipasshub.passstage.cloud/v1/1919006000/totali"

    #         data = {
    #             "grant_type": "client_credentials",
    #             "scope": "sdi"
    #         }

    #         # Get Token JWT
    #         try:
    #             response = requests.post(
    #                 endpoint_url,
    #                 data=data,
    #                 cert=(cert_path, cert_key_path),
    #                 verify=ca_cert_path
    #             )

    #             if response.status_code == 200:
    #                 print("Request for JWT TOKEN was successful, Status Code 200. Response content:")
    #                 print(response.text)

    #                 response_data = json.loads(response.text)
    #                 jwt_token = response_data["access_token"]

    #                 headers = {
    #                     "Authorization": f"Bearer {jwt_token}"
    #                 }

    #                 # Save JWT token to a text file
    #                 with open("jwt_token.txt", "w") as file:
    #                     file.write(jwt_token)
    #                 print("JWT token has been saved to jwt_token.txt")

    #                 # Passhub get
    #                 try:
    #                     response = requests.get(passhub_url, headers=headers)
    #                     if response.status_code == 200:
    #                         print("Request for passhub was successful, Status Code 200. Response content:")
    #                         print(response.text)
    #                     else:
    #                         print(f"Request failed with status code {response.status_code}")
    #                         print(response.text)
    #                 except requests.exceptions.RequestException as e:
    #                     print(f"Request failed with error: {e}")

    #             else:
    #                 print(f"Request failed with status code {response.status_code}")
    #                 print(response.text)
    #         except requests.exceptions.RequestException as e:
    #             print(f"Request failed with error: {e}")





    class MyUser(TaskSet):

        @task
        def get_fatture(self):

            #file_path = "../cert/jwt_token.txt"  
            file_path = "jwt_token.txt"
            with open(file_path, "r") as file:
                line = file.readline()

            jwt_token = line.strip() 

            
            headers = {
                "Authorization": f"Bearer {jwt_token}",
                "Content-Type": "application/json"  # Adjust the content type as needed
            }
            url = f"/v1/{idinstallazione}/totali"
            self.client.get(url, headers=headers)


        @task
        def get_datiTrasmittente(self):

            file_path = "jwt_token.txt"  
            with open(file_path, "r") as file:
                line = file.readline()

            jwt_token = line.strip() 

            
            headers = {
                "Authorization": f"Bearer {jwt_token}",
                "Content-Type": "application/json"  # Adjust the content type as needed
            }
            url = f"/v1/{idinstallazione}/DatiTrasmittente"
            self.client.get(url, headers=headers)




    class MyLocust(FastHttpUser):  # Update 'Locust' to 'HttpUser'
        tasks = [MyUser]
        #wait_time = constant(0.2)
        wait_time = between(1,2)
